#include "Workspace/Entry/PutInInvFix.h"
#include "Workspace/Entry/WaterWeaponFix.h"
#include "Workspace/Entry/PackStringFix.h"
#include "Workspace/Entry/ThrottleEvents.h"
#include "Workspace/Entry/UnconsciousFix.h"
#include "Workspace/Entry/DayMusicFix.h"
#include "Workspace/Entry/EnableNpcFix.h"
#include "Workspace/Entry/ClearCriticalStatesOnLoad.h"