#include "Workspace/Entry/PutInInvFix.h"
#include "Workspace/Entry/WaterWeaponFix.h"
#include "Workspace/Entry/InventoryFix.h"
#include "Workspace/Entry/ThrottleEvents.h"
#include "Workspace/Entry/UnconsciousFix.h"
#include "Workspace/Entry/MidnightFix.h"
#include "Workspace/Entry/RemoveLightFix.h"
#include "Workspace/Entry/DayMusicFix.h"